### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Twobit666** [K3rnel-Dev/VenomRat-SourceCode#6]
Tried it on VM, worked the first time. Then when I tried to open it again after restart it isnt opening.
but it opens on a genuine computer? I think it has some sort of anti VM that hides it self after running the app once

**Comment by K3rnel-Dev** [comment]
Hello, you can look at the source code in the repository, the protection mechanism was bypassed, everything that the author of this application included is not my work, if you have no questions, I will close the ticket after 24 hours.
Thx for watching!:D.

**Comment by olinek1080** [comment]
> Hello, you can look at the source code in the repository, the protection mechanism was bypassed, everything that the author of this application included is not my work, if you have no questions, I will close the ticket after 24 hours.
> Thx for watching!:D.

half of the code is encoded by like base64 and smt else

**Comment by K3rnel-Dev** [comment]
Bro, if you found a virus file or virus code, let me know, I will try to remove it and commit the corrected version, okay? I don't know why you create reports if you have source code that can be checked for dangerous parts.
I don’t know what the creator of this application himself put into his software.
